### ISSUE TITLE
UI - Word Mapper - Export

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/wordmapper#10]
As a user who wants to save the data of the current set of aligned words, or import the data from other sets of aligned words from the same document, I want these functions of saving, exporting and importing to be very clear.
### Acceptance Criteria
- [ ] Update the Export button to Save and Import
- [ ] Allow the current set of selections of aligned words to be either saved to the hard drive, saved to the browser or saved to the server
- [ ] Allow to import another set of selections of aligned words from the same document to be imported, by either pasting the data, or by importing a file
### Proposed UI on GitHub:

https://github.com/Harvard-ATG/ATG-UX/commit/870d6ef8dc37def178582c9daeaa6786701c61aa#diff-dfa38f99137fc6eea7989c1ec65cdf81

**Comment by ramiller84** [comment]
This feature, in particular the Save to Hard Drive option, would be best suited to v. 2.0.
