### ISSUE TITLE
Canvas bugs

### ISSUE THREAD

**Issue by ramiller84** [Harvard-ATG/wordmapper#14]
Insecure, import error, and sources.

Testing notes:  Export/import seems to work ONLY if the alignments have been deleted and the page has NOT been refreshed.  When trying to import alignments after refreshing the page, the following error message occurs:

```
An error occurred with the import. Error: Word item (cano) does not map to a valid source (fe545afff3add938bcbff7f124fdd42b2ac21dc3) at: A0W0
```

**Comment by arthurian** [comment]
Note: I haven't been able to replicate this issue so I'm going to close it for now, but we can re-open it later if it comes up again.
