### ISSUE TITLE
Widget should be close, when needed

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/wordmapper#2]
As a user who activated the WordMapper widget, I also want to inactivate it, when I am done with it.
### Acceptance Criteria
- [ ] A "Close" button would remove the Word Mapper widget.
- [ ] The tooltip of the "Close" button shall be right aligned, so that it doesn't bleed out of the display area.
- [ ] A warning modal may be needed if any information may be lost upon the removal of the Word Mapper widget.
### Proposed UI on GitHub:

https://github.com/Harvard-ATG/ATG-UX/commit/e013a20c9394369a6d6d91d3649a47e4877ae85b#diff-529d06a147ef12533ce33e0b401dec54

**Comment by ramiller84** [comment]
Further discussion needed.  This would be better suited to v. 2.0.
