### ISSUE TITLE
Widget buttons consistency

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/wordmapper#3]
As a user who interacts with the WordMapper widget, I need to see consistency with the button labels and tooltips.

### Acceptance Criteria

- [x] The `title` tag causes a tooltip that overlaps with the styled `wordmapper-tooltip` tooltip. Removing this text from the `title` tag also removes it from the styled tooltip. No good.
- [x] The buttons should be consistent with nomenclature. All of them should represent each action with a single verb; the tooltip will provide more information at first, later the users will remember.

### Proposed UI on GitHub:
https://github.com/Harvard-ATG/ATG-UX/commit/4d03936f22f4437ad2d838d2584491343a9d83f6#diff-ae01d8715294112ef3ab5de8540a33ce

**Comment by arthurian** [comment]
@Vittorio2015 I just made this change to the bookmarklet, so check it out. Commit: https://github.com/Harvard-ATG/wordmapper/commit/0a73687ffc899faaaf45b1c20e6abf147bac5283

**Comment by Vittorio2015** [comment]
Great idea to change `title` to `alt`!
