### ISSUE TITLE
UI - Widget buttons with icons

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/wordmapper#4]
As a user who works with the WordMapper widget and frequently selects the button functions, I find that icons can be memorized and recognized faster than words (to the point that the words, eventually, may not longer be needed).

### Acceptance Criteria

- [x] This issue depends on the issue https://github.com/Harvard-ATG/wordmapper/issues/3.
- [ ] Add Font Awesome icons next to each button label

### Proposed UI on GitHub:
https://github.com/Harvard-ATG/ATG-UX/commit/03ab1647e7d0883a509ed206e8de2c49f0076300#diff-ad0eb864635c442c7029894d89e584e4

**Comment by arthurian** [comment]
@Vittorio2015 I just made this change to the bookmarklet, so check it out. Commit: https://github.com/Harvard-ATG/wordmapper/commit/0a73687ffc899faaaf45b1c20e6abf147bac5283

**Comment by Vittorio2015** [comment]
Very cool!
