### ISSUE TITLE
UI - Word Mapper - left nav

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/wordmapper#5]
As a user who frequently interacts with the WordMapper widget, I need a more streamlined version of this widget, and the feature to move the widget to the left hand side of the web page.
### Acceptance Criteria
- [ ] Allow for a button to change the position of the Word Mapper widget from the top to the left hand side of the web page
- [ ] Allow for another button to hide the text of each button and leave just the links
- [ ] Allow for another button to close the Word Mapper widget, per issue https://github.com/Harvard-ATG/wordmapper/issues/2
- [ ] Realign the tooltips
### Proposed UI on GitHub:

https://github.com/Harvard-ATG/ATG-UX/commit/b92323b6cbb88655b47889713c12ea5424e3d82e#diff-1e0c167cb1620d30c03cb6335e0256c5

**Comment by ramiller84** [comment]
We would like to get more user feedback before committing to implementing this feature.  Best suited to v. 2.0.
