### ISSUE TITLE
UI - Word Mapper - Harvard branding

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/wordmapper#6]
As a user who constantly uses a variety of software to do my work, I would greatly appreciate to recognize Harvard products from vendor products.
### Acceptance Criteria
- [ ] Introduce Harvard branding
- [ ] Although the Harvard shield is currently used in the Harvard Guidelines publication (http://guidelines.hwp.harvard.edu/harvard-university-signature), a copy of this asset may need to be copied elsewhere for the conveniency of this product
### Proposed UI on GitHub:

https://github.com/Harvard-ATG/ATG-UX/commit/f6df631eb6a60930aa1adaf0431590a1766997c8#diff-9eb591da57157ecb27b3e21fb1860d16

**Comment by ramiller84** [comment]
We need to get feedback from Mike Hilborn and Mark Schiefsky (product owner).
