### ISSUE TITLE
UI - Word Mapper - Comments

### ISSUE THREAD

**Issue by Vittorio2015** [Harvard-ATG/wordmapper#8]
As a user I need choose to either comment on a single pair of aligned words, or on all the available pairs. I also need to either save all comments, or cancel.

### Acceptance Criteria

- [x] Introduce Edit buttons to enable comment input forms of each pair of aligned words
- [x] Introduce an Edit button to enable or disable all comment input forms 

### Proposed UI on GitHub:
https://github.com/Harvard-ATG/ATG-UX/commit/88f6ba6a3c6dee09160883c5b4744c3f80ca87ce#diff-e1d22141c3b861ecc5b96fc310005729

**Comment by ramiller84** [comment]
The top pencil icon might be clearer to the user if it is an "Edit all" button or something similar.
